# A script to get a user jwt for Forsta

source ./forsta_library.sh

echo "-----------------------------------------------------------"
echo "This script generates a jwt for the forsta.io platform."
echo "A jwt will allow authenticate a user in the Forsta Messenger Client."
echo "This is for test purposes only."
echo "In deployment jwts should be generated by the server in real time."
echo "-----------------------------------------------------------"

printf "\nPlease login to generate a jwt for that user.\n"

authenticate
echo "JWT:"
echo $auth_token
